# Generated by Django 5.0.6 on 2024-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=100)),
                ('casilla', models.CharField(max_length=100)),
                ('votosmorenapvpt', models.IntegerField()),
                ('votosmc', models.IntegerField()),
                ('votospripanprd', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
